language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: nTIgdzNpfaQNvOxhRVTgfy0n5b9RjXiOlneBUqFISkYEL9WM3aLqarcYtMtB8l7ER8CgvviEjo0mfJ0uwFPYJJ9d4gDG+JPydwN63aJ3jxlCt4t0UvKzko/VQyRQz0yHdBolnaqTWzwLrjbTgPtHOhsm9b2bh9iyuz5IQFcWQhI/sp+QovL4t77gxjYyrhsAGnbc35FCcIB94T+cEtFvtRGxhO7ZtuvtFWL7DalkPXPeQ0hXHeMM4o6R6hxGZRZaR8tFL0hvXPKpYpyLV5LolsfNa6SAbFlswZvWglNQZ1nJ7QGn7m/yGiuPwg/Uf3lNP2zZfc2ryrWAPro+T8ij2ZVo67JtpzKTj2hHIpH8MKGmUwAZhXxrNxwtAgIL1NNM+RAMZH69Hu5ovVIjeFKZ+hlCu+UpM4UIwAjoCJcqnN9gmpJALqKlpt8po5YP8tFnUFXUj/OaJwcE8zqDJMzt4+mAtF8iczHqm+pZhsTLslUrfYdSpJgLVSY6hQGE4yfWmdSg4MB1/wwELak/HitBgPw0giCeoecFYj45SLhE7a3yr0uXCUtm/ngEbK9bXwgBtlFYUzkVcQQj9Ddd/JlpCdgFteQRx4AX0mJEpalOftwzNqCi9BcRlBTdwqTBzeq4DEdAUvMvD9ET/RaLtMs8Jo9gfPL8SaoDtohwWIy88Ak=
    app: green-rancid-tomatillos
    skip_cleanup: true
    branches: main
